# Generated by Django 5.1.7 on 2025-03-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=20)),
                ("complete", models.BooleanField(default=False)),
                ("task_description", models.TextField(max_length=100)),
                ("date_added", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
