# Generated by Django 5.2.3 on 2025-06-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_added',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(max_length=200),
        ),
    ]
