# Generated by Django 5.1.7 on 2025-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user",
        ),
        migrations.AddField(
            model_name="tasks",
            name="deadline",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
