# Generated by Django 5.1.7 on 2025-03-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_delete_user_tasks_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="complete",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
    ]
